###
GET http://localhost:5000/api

###
GET http://localhost:5000/api/showproducts

###
POST http://localhost:5000/api/showproducts
Content-Type: application/json

{
    "name":"Samsung TV",
    "desc":"Smart Tv",
    "price":45000,
    "img":"/images/samsung.jpg",
    "status":"unpublish"
}

###
DELETE http://localhost:5000/api/showproducts/6394867a9f36ebcd36a33d47