//for mutiple data

###
GET http://localhost:5000/api

// for single data
###
GET http://localhost:5000/api/632417d3c154766378d15cdf

// create record
###
POST http://localhost:5000/api
Content-Type: application/json

{
    "name":"LGvt4 TV",
    "desc":"HD 42 inch LED",
    "price":45000,
    "img":"/upload/lgtvv.jpeg"
}

//for delete single record

###
DELETE http://localhost:5000/api/633007d6910c7804df62ca26

###
PUT http://localhost:5000/api/