//for mutiple data

###
GET http://localhost:5000/api

// for single data
###
GET http://localhost:5000/api/63313782adc3537be5c7725c

// create record
###
POST http://localhost:5000/api
Content-Type: application/json

{
    "name":"LGvt4233 TV",
    "desc":"HD 45 inch LED",
    "price":55000,
    "img":"/upload/lgtvv.jpeg"
}

//for delete single record

###
DELETE http://localhost:5000/api/63313755adc3537be5c7724f

###
PUT http://localhost:5000/api/